import type { Metadata } from "next";
import { ClerkProvider, RedirectToSignIn, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton, SignIn } from "@clerk/nextjs";
import { Geist, Geist_Mono, Poppins, Syncopate } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { auth, currentUser } from "@clerk/nextjs/server";

const poppins = Poppins({
  weight: ["200", "300", "400"],
  variable: "--font-poppins-400",
  subsets: ["latin"],
  display: "swap",
});
const syncopate = Syncopate({
  weight: ["400"],
  variable: "--font-syncopate-400",
  subsets: ["latin"],
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { userId } = await auth();
  const user = await currentUser();
  // const pathname = usePathname(); 
  // const showNavbar = pathname !== "/game";
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} ${syncopate.variable} font-poppins antialiased`}>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16 fixed top-0"> */}
            <SignedOut>
              <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
              {/* <UserButton /> */}
            </SignedIn>
          {/* </header> */}
          {children}
          {user && (
            <Navbar />
          )}
        </body>
      </html>
    </ClerkProvider>
  );
}


